### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by MaxwellJung**
See list of commits below for all implemented features.
Test each feature using code NSQSSS.
After testing all features, merge this PR to main and overwrite 7HSKW with NSQSSS.

Features missing from initial proposal are:
- ~~Torb turret~~
- ~~Venture changes~~
- HP bug fix

### CODE REVIEW

**Comment by MaxwellJung** [comment]
add back 222 role lock

**Comment by MaxwellJung** [comment]
updated dev build code with the last 2 fixes

**Comment by MaxwellJung** [comment]
NSQSSS has been updated with lemonhead's changes

**Comment by MaxwellJung** [comment]
updated NSQSSS

**Comment by MaxwellJung** [comment]
updated NSQSSS

**Review by ieToastie — COMMENTED** [review]
I've looked over all the code and tested everything in game myself, we are ready to merge to main

**Review by ieToastie — APPROVED** [review]

**Comment by MaxwellJung** [comment]
cool just make sure to disable all the april fools modes when you flash gamemode

**Pull request merged**
